Extension { #name : #DojoNodeQuery }

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> adapterRegistry [

	^ self create: DojoAdapterRegistry
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dataApiIdentity [

	^ self create: DojoIdentity
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dataApiNotification [

	^ self create: DojoNotification
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dataApiRead [

	^ self create: DojoRead
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dataApiRequest [

	^ self create: DojoRequest
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dataApiWrite [

	^ self create: DojoWrite
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dataItemFileReadStore [

	^ self create: DojoItemFileReadStore
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dataItemFileWriteStore [

	^ self create: DojoItemFileWriteStore
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dataUtilSimpleFetch [

	^ self create: DojoSimpleFetch
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dndAutoSource [

	^ self create: DojoAutoSource
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dndAvatar [

	^ self create: DojoAvatar
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dndContainer [

	^ self create: DojoContainer
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dndItem [

	^ self create: DojoItem
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dndManager [

	^ self create: DojoManager
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dndMoveable [

	^ self create: DojoMoveable
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dndMover [

	^ self create: DojoMover
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dndSelector [

	^ self create: DojoSelector
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dndSource [

	^ self create: DojoSource
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dndTarget [

	^ self create: DojoTarget
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> dndTimedMoveable [

	^ self create: DojoTimedMoveable
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> itemFileReadStore [

	^ self create: DojoItemFileReadStore
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> itemFileWriteStore [

	^ self create: DojoItemFileWriteStore
]

{ #category : #'*DojoToolkit-Objects-generated' }
DojoNodeQuery >> simpleFetch [

	^ self create: DojoSimpleFetch
]
