Extension { #name : #DojoAbstractQuery }

{ #category : #'*DojoToolkit-DojoX-generated' }
DojoAbstractQuery >> dataQueryReadStore [

	^ self create: DojoxDataQueryReadStore
]

{ #category : #'*DojoToolkit-DojoX-generated' }
DojoAbstractQuery >> dojoxContentPane [

	^ self create: DojoxContentPane
]

{ #category : #'*DojoToolkit-DojoX-generated' }
DojoAbstractQuery >> dragPane [

	^ self create: DojoxDragPane
]

{ #category : #'*DojoToolkit-DojoX-generated' }
DojoAbstractQuery >> floatingPane [

	^ self create: DojoxFloatingPane
]

{ #category : #'*DojoToolkit-DojoX-generated' }
DojoAbstractQuery >> widgetDialog [

	^ self create: DojoxWidgetDialog
]
