Extension { #name : #WAHtmlCanvas }

{ #category : #'*DojoToolkit-DojoX-generated' }
WAHtmlCanvas >> dojoxContentPane [
	" Dojo widget: dojox.layout.ContentPane "

	^ self div dojoType: DojoxContentPane
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WAHtmlCanvas >> dojoxContentPane: aBlock [
	" Dojo widget: dojox.layout.ContentPane "

	self dojoxContentPane with: aBlock
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WAHtmlCanvas >> dojoxDragPane [
	" Dojo widget: dojox.layout.DragPane "

	^ self div dojoType: DojoxDragPane
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WAHtmlCanvas >> dojoxDragPane: aBlock [
	" Dojo widget: dojox.layout.DragPane "

	self dojoxDragPane with: aBlock
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WAHtmlCanvas >> dojoxFloatingPane [
	" Dojo widget: dojox.layout.FloatingPane "

	^ self div dojoType: DojoxFloatingPane
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WAHtmlCanvas >> dojoxFloatingPane: aBlock [
	" Dojo widget: dojox.layout.FloatingPane "

	self dojoxFloatingPane with: aBlock
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WAHtmlCanvas >> dojoxWidgetDialog [
	" Dojo widget: dojox.widget.Dialog "

	^ self div dojoType: DojoxWidgetDialog
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WAHtmlCanvas >> dojoxWidgetDialog: aBlock [
	" Dojo widget: dojox.widget.Dialog "

	self dojoxWidgetDialog with: aBlock
]
