Extension { #name : #WARenderCanvas }

{ #category : #'*DojoToolkit-DojoX-generated' }
WARenderCanvas >> dojoxContentPane [
	" Dojo widget: dojox.layout.ContentPane "

	^ self div dojoType: DojoxContentPane
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WARenderCanvas >> dojoxContentPane: aBlock [
	" Dojo widget: dojox.layout.ContentPane "

	self dojoxContentPane with: aBlock
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WARenderCanvas >> dojoxDragPane [
	" Dojo widget: dojox.layout.DragPane "

	^ self div dojoType: DojoxDragPane
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WARenderCanvas >> dojoxDragPane: aBlock [
	" Dojo widget: dojox.layout.DragPane "

	self dojoxDragPane with: aBlock
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WARenderCanvas >> dojoxFloatingPane [
	" Dojo widget: dojox.layout.FloatingPane "

	^ self div dojoType: DojoxFloatingPane
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WARenderCanvas >> dojoxFloatingPane: aBlock [
	" Dojo widget: dojox.layout.FloatingPane "

	self dojoxFloatingPane with: aBlock
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WARenderCanvas >> dojoxWidgetDialog [
	" Dojo widget: dojox.widget.Dialog "

	^ self div dojoType: DojoxWidgetDialog
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WARenderCanvas >> dojoxWidgetDialog: aBlock [
	" Dojo widget: dojox.widget.Dialog "

	self dojoxWidgetDialog with: aBlock
]
