Extension { #name : #WARenderCanvas }

{ #category : #'*DojoToolkit-DojoX-generated' }
WARenderCanvas >> dojoxContentPane [
	" Dojo widget: dojox.layout.ContentPane "

	^ self div dojoType: DojoxContentPane
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WARenderCanvas >> dojoxContentPane: aBlock [
	" Dojo widget: dojox.layout.ContentPane "

	self dojoxContentPane with: aBlock
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WARenderCanvas >> dragPane [
	" Dojo widget: dojox.layout.DragPane "

	^ self div dojoType: DojoxDragPane
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WARenderCanvas >> dragPane: aBlock [
	" Dojo widget: dojox.layout.DragPane "

	self dragPane with: aBlock
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WARenderCanvas >> floatingPane [
	" Dojo widget: dojox.layout.FloatingPane "

	^ self div dojoType: DojoxFloatingPane
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WARenderCanvas >> floatingPane: aBlock [
	" Dojo widget: dojox.layout.FloatingPane "

	self floatingPane with: aBlock
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WARenderCanvas >> widgetDialog [
	" Dojo widget: dojox.widget.Dialog "

	^ self div dojoType: DojoxWidgetDialog
]

{ #category : #'*DojoToolkit-DojoX-generated' }
WARenderCanvas >> widgetDialog: aBlock [
	" Dojo widget: dojox.widget.Dialog "

	self widgetDialog with: aBlock
]
