"
A validating, serializable, range-bound date text box with a drop down calendar Example: new dijit.form.DateTextBox({value: new Date(2009, 0, 20)}) Example: <input dojotype='dijit.form.DateTextBox' value='2009-01-20'>
"
Class {
	#name : #DijitDateTextBox,
	#superclass : #DijitDateTimeTextBox,
	#category : 'DojoToolkit-Widgets'
}

{ #category : #'accessing-generated' }
DijitDateTextBox class >> functionName [

	^ 'dijit.form.DateTextBox'
]
