Extension { #name : #DojoNodeQuery }

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> accordionContainer [

	^ self create: DijitAccordionContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> accordionPane [

	^ self create: DijitAccordionPane
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> backgroundIframe [

	^ self create: DijitBackgroundIframe
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> borderContainer [

	^ self create: DijitBorderContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> button [

	^ self create: DijitButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> calendar [

	^ self create: DijitCalendar
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> checkBox [

	^ self create: DijitCheckBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> checkedMenuItem [

	^ self create: DijitCheckedMenuItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> colorPalette [

	^ self create: DijitColorPalette
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> comboBox [

	^ self create: DijitComboBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> comboButton [

	^ self create: DijitComboButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> contentPane [

	^ self create: DijitContentPane
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> currencyTextBox [

	^ self create: DijitCurrencyTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> dateTextBox [

	^ self create: DijitDateTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> dateTimeTextBox [

	^ self create: DijitDateTimeTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> declaration [

	^ self create: DijitDeclaration
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> dialog [

	^ self create: DijitDialog
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> dialogUnderlay [

	^ self create: DijitDialogUnderlay
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> dropDownButton [

	^ self create: DijitDropDownButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> dye [

	^ self create: DijitDye
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> editor [

	^ self create: DijitEditor
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> editorRichText [

	^ self create: DijitRichText
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> filteringSelect [

	^ self create: DijitFilteringSelect
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> form [

	^ self create: DijitForm
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> formSelectWidget [

	^ self create: DijitFormSelectWidget
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> formValueWidget [

	^ self create: DijitFormValueWidget
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> formWidget [

	^ self create: DijitFormWidget
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> horizontalRule [

	^ self create: DijitHorizontalRule
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> horizontalRuleLabels [

	^ self create: DijitHorizontalRuleLabels
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> horizontalSlider [

	^ self create: DijitHorizontalSlider
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> inlineEditBox [

	^ self create: DijitInlineEditBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> layoutContainer [

	^ self create: DijitLayoutContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> layoutWidget [

	^ self create: DijitLayoutWidget
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> linkPane [

	^ self create: DijitLinkPane
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> mappedTextBox [

	^ self create: DijitMappedTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> menu [

	^ self create: DijitMenu
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> menuBar [

	^ self create: DijitMenuBar
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> menuBarItem [

	^ self create: DijitMenuBarItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> menuBase [

	^ self create: DijitMenuBase
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> menuItem [

	^ self create: DijitMenuItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> menuSeparator [

	^ self create: DijitMenuSeparator
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> multiSelect [

	^ self create: DijitMultiSelect
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> numberSpinner [

	^ self create: DijitNumberSpinner
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> numberTextBox [

	^ self create: DijitNumberTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> popupMenuBarItem [

	^ self create: DijitPopupMenuBarItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> popupMenuItem [

	^ self create: DijitPopupMenuItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> progressBar [

	^ self create: DijitProgressBar
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> radioButton [

	^ self create: DijitRadioButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> rangeBoundTextBox [

	^ self create: DijitRangeBoundTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> scrollingTabController [

	^ self create: DijitScrollingTabController
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> select [

	^ self create: DijitSelect
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> simpleTextarea [

	^ self create: DijitSimpleTextarea
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> spinner [

	^ self create: DijitSpinner
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> splitContainer [

	^ self create: DijitSplitContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> stackContainer [

	^ self create: DijitStackContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> stackController [

	^ self create: DijitStackController
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> tabContainer [

	^ self create: DijitTabContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> tabContainerBase [

	^ self create: DijitTabContainerBase
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> tabController [

	^ self create: DijitTabController
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> textBox [

	^ self create: DijitTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> textarea [

	^ self create: DijitTextarea
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> timeTextBox [

	^ self create: DijitTimeTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> titlePane [

	^ self create: DijitTitlePane
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> toggleButton [

	^ self create: DijitToggleButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> toolbar [

	^ self create: DijitToolbar
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> toolbarSeparator [

	^ self create: DijitToolbarSeparator
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> tooltip [

	^ self create: DijitTooltip
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> tooltipDialog [

	^ self create: DijitTooltipDialog
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> tree [

	^ self create: DijitTree
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> treeDndContainer [

	^ self create: DijitDndContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> treeDndSelector [

	^ self create: DijitDndSelector
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> treeDndSource [

	^ self create: DijitDndSource
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> treeForestStoreModel [

	^ self create: DijitForestStoreModel
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> treeModel [

	^ self create: DijitModel
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> treeStoreModel [

	^ self create: DijitTreeStoreModel
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> typematicStop [

	^ self create: DijitStop
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> validationTextBox [

	^ self create: DijitValidationTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> verticalRule [

	^ self create: DijitVerticalRule
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> verticalRuleLabels [

	^ self create: DijitVerticalRuleLabels
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> verticalSlider [

	^ self create: DijitVerticalSlider
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> widget [

	^ self create: DijitWidget
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoNodeQuery >> widgetSet [

	^ self create: DijitWidgetSet
]
