Extension { #name : #DojoAbstractQuery }

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> accordionContainer [

	^ self create: DijitAccordionContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> accordionPane [

	^ self create: DijitAccordionPane
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> backgroundIframe [

	^ self create: DijitBackgroundIframe
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> borderContainer [

	^ self create: DijitBorderContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> button [

	^ self create: DijitButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> calendar [

	^ self create: DijitCalendar
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> checkBox [

	^ self create: DijitCheckBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> checkedMenuItem [

	^ self create: DijitCheckedMenuItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> colorPalette [

	^ self create: DijitColorPalette
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> comboBox [

	^ self create: DijitComboBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> comboButton [

	^ self create: DijitComboButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> contentPane [

	^ self create: DijitContentPane
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> currencyTextBox [

	^ self create: DijitCurrencyTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> dateTextBox [

	^ self create: DijitDateTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> dateTimeTextBox [

	^ self create: DijitDateTimeTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> declaration [

	^ self create: DijitDeclaration
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> dialog [

	^ self create: DijitDialog
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> dialogUnderlay [

	^ self create: DijitDialogUnderlay
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> dropDownButton [

	^ self create: DijitDropDownButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> dye [

	^ self create: DijitDye
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> editor [

	^ self create: DijitEditor
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> editorRichText [

	^ self create: DijitRichText
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> filteringSelect [

	^ self create: DijitFilteringSelect
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> form [

	^ self create: DijitForm
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> formSelectWidget [

	^ self create: DijitFormSelectWidget
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> formWidget [

	^ self create: DijitFormWidget
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> horizontalRule [

	^ self create: DijitHorizontalRule
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> horizontalRuleLabels [

	^ self create: DijitHorizontalRuleLabels
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> horizontalSlider [

	^ self create: DijitHorizontalSlider
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> inlineEditBox [

	^ self create: DijitInlineEditBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> layoutContainer [

	^ self create: DijitLayoutContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> layoutWidget [

	^ self create: DijitLayoutWidget
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> linkPane [

	^ self create: DijitLinkPane
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> mappedTextBox [

	^ self create: DijitMappedTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> menu [

	^ self create: DijitMenu
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> menuBar [

	^ self create: DijitMenuBar
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> menuBarItem [

	^ self create: DijitMenuBarItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> menuBase [

	^ self create: DijitMenuBase
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> menuItem [

	^ self create: DijitMenuItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> menuSeparator [

	^ self create: DijitMenuSeparator
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> multiSelect [

	^ self create: DijitMultiSelect
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> numberSpinner [

	^ self create: DijitNumberSpinner
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> numberTextBox [

	^ self create: DijitNumberTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> popupMenuBarItem [

	^ self create: DijitPopupMenuBarItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> popupMenuItem [

	^ self create: DijitPopupMenuItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> progressBar [

	^ self create: DijitProgressBar
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> radioButton [

	^ self create: DijitRadioButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> rangeBoundTextBox [

	^ self create: DijitRangeBoundTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> scrollingTabController [

	^ self create: DijitScrollingTabController
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> select [

	^ self create: DijitSelect
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> simpleTextarea [

	^ self create: DijitSimpleTextarea
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> spinner [

	^ self create: DijitSpinner
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> splitContainer [

	^ self create: DijitSplitContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> stackContainer [

	^ self create: DijitStackContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> stackController [

	^ self create: DijitStackController
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> tabContainer [

	^ self create: DijitTabContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> tabContainerBase [

	^ self create: DijitTabContainerBase
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> tabController [

	^ self create: DijitTabController
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> textBox [

	^ self create: DijitTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> textarea [

	^ self create: DijitTextarea
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> timeTextBox [

	^ self create: DijitTimeTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> titlePane [

	^ self create: DijitTitlePane
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> toggleButton [

	^ self create: DijitToggleButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> toolbar [

	^ self create: DijitToolbar
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> toolbarSeparator [

	^ self create: DijitToolbarSeparator
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> tooltip [

	^ self create: DijitTooltip
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> tooltipDialog [

	^ self create: DijitTooltipDialog
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> tree [

	^ self create: DijitTree
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> treeDndContainer [

	^ self create: DijitTreeDndContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> treeDndSelector [

	^ self create: DijitTreeDndSelector
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> treeDndSource [

	^ self create: DijitTreeDndSource
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> treeForestStoreModel [

	^ self create: DijitForestStoreModel
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> treeModel [

	^ self create: DijitModel
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> treeStoreModel [

	^ self create: DijitTreeStoreModel
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> typematicStop [

	^ self create: DijitStop
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> validationTextBox [

	^ self create: DijitValidationTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> verticalRule [

	^ self create: DijitVerticalRule
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> verticalRuleLabels [

	^ self create: DijitVerticalRuleLabels
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> verticalSlider [

	^ self create: DijitVerticalSlider
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> widget [

	^ self create: DijitWidget
]

{ #category : #'*DojoToolkit-Widgets-generated' }
DojoAbstractQuery >> widgetSet [

	^ self create: DijitWidgetSet
]
