Extension { #name : #WAHtmlCanvas }

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoAccordionContainer [
	" Dojo widget: dijit.layout.AccordionContainer "

	^ self div dojoType: DijitAccordionContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoAccordionContainer: aBlock [
	" Dojo widget: dijit.layout.AccordionContainer "

	self dojoAccordionContainer with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoAccordionPane [
	" Dojo widget: dijit.layout.AccordionPane "

	^ self div dojoType: DijitAccordionPane
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoAccordionPane: aBlock [
	" Dojo widget: dijit.layout.AccordionPane "

	self dojoAccordionPane with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoBorderContainer [
	" Dojo widget: dijit.layout.BorderContainer "

	^ self div dojoType: DijitBorderContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoBorderContainer: aBlock [
	" Dojo widget: dijit.layout.BorderContainer "

	self dojoBorderContainer with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoButton [
	" Dojo widget: dijit.form.Button "

	^ self button dojoType: DijitButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoButton: aBlock [
	" Dojo widget: dijit.form.Button "

	self dojoButton with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoCalendar [
	" Dojo widget: dijit.Calendar "

	^ self div dojoType: DijitCalendar
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoCalendar: aBlock [
	" Dojo widget: dijit.Calendar "

	self dojoCalendar with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoCheckBox [
	" Dojo widget: dijit.form.CheckBox "

	^ self div dojoType: DijitCheckBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoCheckBox: aBlock [
	" Dojo widget: dijit.form.CheckBox "

	self dojoCheckBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoCheckedMenuItem [
	" Dojo widget: dijit.CheckedMenuItem "

	^ self div dojoType: DijitCheckedMenuItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoCheckedMenuItem: aBlock [
	" Dojo widget: dijit.CheckedMenuItem "

	self dojoCheckedMenuItem with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoColorPalette [
	" Dojo widget: dijit.ColorPalette "

	^ self div dojoType: DijitColorPalette
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoColorPalette: aBlock [
	" Dojo widget: dijit.ColorPalette "

	self dojoColorPalette with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoComboBox [
	" Dojo widget: dijit.form.ComboBox "

	^ self textInput dojoType: DijitComboBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoComboBox: aBlock [
	" Dojo widget: dijit.form.ComboBox "

	self dojoComboBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoComboButton [
	" Dojo widget: dijit.form.ComboButton "

	^ self div dojoType: DijitComboButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoComboButton: aBlock [
	" Dojo widget: dijit.form.ComboButton "

	self dojoComboButton with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoContentPane [
	" Dojo widget: dijit.layout.ContentPane "

	^ self div dojoType: DijitContentPane
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoContentPane: aBlock [
	" Dojo widget: dijit.layout.ContentPane "

	self dojoContentPane with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoCurrencyTextBox [
	" Dojo widget: dijit.form.CurrencyTextBox "

	^ self textInput dojoType: DijitCurrencyTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoCurrencyTextBox: aBlock [
	" Dojo widget: dijit.form.CurrencyTextBox "

	self dojoCurrencyTextBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoDateTextBox [
	" Dojo widget: dijit.form.DateTextBox "

	^ self textInput dojoType: DijitDateTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoDateTextBox: aBlock [
	" Dojo widget: dijit.form.DateTextBox "

	self dojoDateTextBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoDateTimeTextBox [
	" Dojo widget: dijit.form.DateTimeTextBox "

	^ self textInput dojoType: DijitDateTimeTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoDateTimeTextBox: aBlock [
	" Dojo widget: dijit.form.DateTimeTextBox "

	self dojoDateTimeTextBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoDeclaration [
	" Dojo widget: dijit.Declaration "

	^ self div dojoType: DijitDeclaration
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoDeclaration: aBlock [
	" Dojo widget: dijit.Declaration "

	self dojoDeclaration with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoDialog [
	" Dojo widget: dijit.Dialog "

	^ self div dojoType: DijitDialog
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoDialog: aBlock [
	" Dojo widget: dijit.Dialog "

	self dojoDialog with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoDialogUnderlay [
	" Dojo widget: dijit.DialogUnderlay "

	^ self div dojoType: DijitDialogUnderlay
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoDialogUnderlay: aBlock [
	" Dojo widget: dijit.DialogUnderlay "

	self dojoDialogUnderlay with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoDropDownButton [
	" Dojo widget: dijit.form.DropDownButton "

	^ self div dojoType: DijitDropDownButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoDropDownButton: aBlock [
	" Dojo widget: dijit.form.DropDownButton "

	self dojoDropDownButton with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoEditor [
	" Dojo widget: dijit.Editor "

	^ self div dojoType: DijitEditor
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoEditor: aBlock [
	" Dojo widget: dijit.Editor "

	self dojoEditor with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoEditorRichText [
	" Dojo widget: dijit.editor.RichText "

	^ self div dojoType: DijitRichText
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoEditorRichText: aBlock [
	" Dojo widget: dijit.editor.RichText "

	self dojoEditorRichText with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoFilteringSelect [
	" Dojo widget: dijit.form.FilteringSelect "

	^ self textInput dojoType: DijitFilteringSelect
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoFilteringSelect: aBlock [
	" Dojo widget: dijit.form.FilteringSelect "

	self dojoFilteringSelect with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoForm [
	" Dojo widget: dijit.form.Form "

	^ (self brush: DojoWidgetFormTag new) dojoType: DijitForm
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoForm: aBlock [
	" Dojo widget: dijit.form.Form "

	self dojoForm with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoFormSelectWidget [
	" Dojo widget: dijit.form.FormSelectWidget "

	^ self div dojoType: DijitFormSelectWidget
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoFormSelectWidget: aBlock [
	" Dojo widget: dijit.form.FormSelectWidget "

	self dojoFormSelectWidget with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoHorizontalRule [
	" Dojo widget: dijit.form.HorizontalRule "

	^ self div dojoType: DijitHorizontalRule
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoHorizontalRule: aBlock [
	" Dojo widget: dijit.form.HorizontalRule "

	self dojoHorizontalRule with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoHorizontalRuleLabels [
	" Dojo widget: dijit.form.HorizontalRuleLabels "

	^ self div dojoType: DijitHorizontalRuleLabels
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoHorizontalRuleLabels: aBlock [
	" Dojo widget: dijit.form.HorizontalRuleLabels "

	self dojoHorizontalRuleLabels with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoHorizontalSlider [
	" Dojo widget: dijit.form.HorizontalSlider "

	^ self div dojoType: DijitHorizontalSlider
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoHorizontalSlider: aBlock [
	" Dojo widget: dijit.form.HorizontalSlider "

	self dojoHorizontalSlider with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoInlineEditBox [
	" Dojo widget: dijit.InlineEditBox "

	^ self div dojoType: DijitInlineEditBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoInlineEditBox: aBlock [
	" Dojo widget: dijit.InlineEditBox "

	self dojoInlineEditBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoLayoutContainer [
	" Dojo widget: dijit.layout.LayoutContainer "

	^ self div dojoType: DijitLayoutContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoLayoutContainer: aBlock [
	" Dojo widget: dijit.layout.LayoutContainer "

	self dojoLayoutContainer with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoLayoutWidget [
	" Dojo widget: dijit.layout.LayoutWidget "

	^ self div dojoType: DijitLayoutWidget
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoLayoutWidget: aBlock [
	" Dojo widget: dijit.layout.LayoutWidget "

	self dojoLayoutWidget with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoLinkPane [
	" Dojo widget: dijit.layout.LinkPane "

	^ self div dojoType: DijitLinkPane
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoLinkPane: aBlock [
	" Dojo widget: dijit.layout.LinkPane "

	self dojoLinkPane with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoMappedTextBox [
	" Dojo widget: dijit.form.MappedTextBox "

	^ self textInput dojoType: DijitMappedTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoMappedTextBox: aBlock [
	" Dojo widget: dijit.form.MappedTextBox "

	self dojoMappedTextBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoMenu [
	" Dojo widget: dijit.Menu "

	^ self div dojoType: DijitMenu
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoMenu: aBlock [
	" Dojo widget: dijit.Menu "

	self dojoMenu with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoMenuBar [
	" Dojo widget: dijit.MenuBar "

	^ self div dojoType: DijitMenuBar
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoMenuBar: aBlock [
	" Dojo widget: dijit.MenuBar "

	self dojoMenuBar with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoMenuBarItem [
	" Dojo widget: dijit.MenuBarItem "

	^ self div dojoType: DijitMenuBarItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoMenuBarItem: aBlock [
	" Dojo widget: dijit.MenuBarItem "

	self dojoMenuBarItem with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoMenuBase [
	" Dojo widget: dijit.MenuBase "

	^ self div dojoType: DijitMenuBase
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoMenuBase: aBlock [
	" Dojo widget: dijit.MenuBase "

	self dojoMenuBase with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoMenuItem [
	" Dojo widget: dijit.MenuItem "

	^ self div dojoType: DijitMenuItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoMenuItem: aBlock [
	" Dojo widget: dijit.MenuItem "

	self dojoMenuItem with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoMenuSeparator [
	" Dojo widget: dijit.MenuSeparator "

	^ self div dojoType: DijitMenuSeparator
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoMenuSeparator: aBlock [
	" Dojo widget: dijit.MenuSeparator "

	self dojoMenuSeparator with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoMultiSelect [
	" Dojo widget: dijit.form.MultiSelect "

	^ self div dojoType: DijitMultiSelect
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoMultiSelect: aBlock [
	" Dojo widget: dijit.form.MultiSelect "

	self dojoMultiSelect with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoNumberSpinner [
	" Dojo widget: dijit.form.NumberSpinner "

	^ self textInput dojoType: DijitNumberSpinner
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoNumberSpinner: aBlock [
	" Dojo widget: dijit.form.NumberSpinner "

	self dojoNumberSpinner with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoNumberTextBox [
	" Dojo widget: dijit.form.NumberTextBox "

	^ self textInput dojoType: DijitNumberTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoNumberTextBox: aBlock [
	" Dojo widget: dijit.form.NumberTextBox "

	self dojoNumberTextBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoPopupMenuBarItem [
	" Dojo widget: dijit.PopupMenuBarItem "

	^ self div dojoType: DijitPopupMenuBarItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoPopupMenuBarItem: aBlock [
	" Dojo widget: dijit.PopupMenuBarItem "

	self dojoPopupMenuBarItem with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoPopupMenuItem [
	" Dojo widget: dijit.PopupMenuItem "

	^ self div dojoType: DijitPopupMenuItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoPopupMenuItem: aBlock [
	" Dojo widget: dijit.PopupMenuItem "

	self dojoPopupMenuItem with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoProgressBar [
	" Dojo widget: dijit.ProgressBar "

	^ self div dojoType: DijitProgressBar
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoProgressBar: aBlock [
	" Dojo widget: dijit.ProgressBar "

	self dojoProgressBar with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoRadioButton [
	" Dojo widget: dijit.form.RadioButton "

	^ self div dojoType: DijitRadioButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoRadioButton: aBlock [
	" Dojo widget: dijit.form.RadioButton "

	self dojoRadioButton with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoRangeBoundTextBox [
	" Dojo widget: dijit.form.RangeBoundTextBox "

	^ self textInput dojoType: DijitRangeBoundTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoRangeBoundTextBox: aBlock [
	" Dojo widget: dijit.form.RangeBoundTextBox "

	self dojoRangeBoundTextBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoScrollingTabController [
	" Dojo widget: dijit.layout.ScrollingTabController "

	^ self div dojoType: DijitScrollingTabController
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoScrollingTabController: aBlock [
	" Dojo widget: dijit.layout.ScrollingTabController "

	self dojoScrollingTabController with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoSelect [
	" Dojo widget: dijit.form.Select "

	^ self div dojoType: DijitSelect
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoSelect: aBlock [
	" Dojo widget: dijit.form.Select "

	self dojoSelect with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoSimpleTextarea [
	" Dojo widget: dijit.form.SimpleTextarea "

	^ self textArea dojoType: DijitSimpleTextarea
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoSimpleTextarea: aBlock [
	" Dojo widget: dijit.form.SimpleTextarea "

	self dojoSimpleTextarea with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoSpinner [
	" Dojo widget: dijit.form.Spinner "

	^ self textInput dojoType: DijitSpinner
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoSpinner: aBlock [
	" Dojo widget: dijit.form.Spinner "

	self dojoSpinner with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoSplitContainer [
	" Dojo widget: dijit.layout.SplitContainer "

	^ self div dojoType: DijitSplitContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoSplitContainer: aBlock [
	" Dojo widget: dijit.layout.SplitContainer "

	self dojoSplitContainer with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoStackContainer [
	" Dojo widget: dijit.layout.StackContainer "

	^ self div dojoType: DijitStackContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoStackContainer: aBlock [
	" Dojo widget: dijit.layout.StackContainer "

	self dojoStackContainer with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoStackController [
	" Dojo widget: dijit.layout.StackController "

	^ self div dojoType: DijitStackController
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoStackController: aBlock [
	" Dojo widget: dijit.layout.StackController "

	self dojoStackController with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoSubmitButton [
	" Dojo widget: dijit.form.Button "
	" does not use WASubmitButtonTag, because Dojo uses the contents of the <button> tag as label "

	^ self button type: 'submit';
		dojoType: DijitButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoSubmitButton: aBlock [
	" Dojo widget: dijit.form.Button "

	self dojoSubmitButton with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTabContainer [
	" Dojo widget: dijit.layout.TabContainer "

	^ self div dojoType: DijitTabContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTabContainer: aBlock [
	" Dojo widget: dijit.layout.TabContainer "

	self dojoTabContainer with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTabContainerBase [
	" Dojo widget: dijit.layout.TabContainerBase "

	^ self div dojoType: DijitTabContainerBase
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTabContainerBase: aBlock [
	" Dojo widget: dijit.layout.TabContainerBase "

	self dojoTabContainerBase with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTabController [
	" Dojo widget: dijit.layout.TabController "

	^ self div dojoType: DijitTabController
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTabController: aBlock [
	" Dojo widget: dijit.layout.TabController "

	self dojoTabController with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTextBox [
	" Dojo widget: dijit.form.TextBox "

	^ self textInput dojoType: DijitTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTextBox: aBlock [
	" Dojo widget: dijit.form.TextBox "

	self dojoTextBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTextarea [
	" Dojo widget: dijit.form.Textarea "

	^ self textArea dojoType: DijitTextarea
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTextarea: aBlock [
	" Dojo widget: dijit.form.Textarea "

	self dojoTextarea with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTimeTextBox [
	" Dojo widget: dijit.form.TimeTextBox "

	^ self textInput dojoType: DijitTimeTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTimeTextBox: aBlock [
	" Dojo widget: dijit.form.TimeTextBox "

	self dojoTimeTextBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTitlePane [
	" Dojo widget: dijit.TitlePane "

	^ self div dojoType: DijitTitlePane
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTitlePane: aBlock [
	" Dojo widget: dijit.TitlePane "

	self dojoTitlePane with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoToggleButton [
	" Dojo widget: dijit.form.ToggleButton "

	^ self div dojoType: DijitToggleButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoToggleButton: aBlock [
	" Dojo widget: dijit.form.ToggleButton "

	self dojoToggleButton with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoToolbar [
	" Dojo widget: dijit.Toolbar "

	^ self div dojoType: DijitToolbar
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoToolbar: aBlock [
	" Dojo widget: dijit.Toolbar "

	self dojoToolbar with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoToolbarSeparator [
	" Dojo widget: dijit.ToolbarSeparator "

	^ self div dojoType: DijitToolbarSeparator
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoToolbarSeparator: aBlock [
	" Dojo widget: dijit.ToolbarSeparator "

	self dojoToolbarSeparator with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTooltip [
	" Dojo widget: dijit.Tooltip "

	^ self div dojoType: DijitTooltip
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTooltip: aBlock [
	" Dojo widget: dijit.Tooltip "

	self dojoTooltip with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTooltipDialog [
	" Dojo widget: dijit.TooltipDialog "

	^ self div dojoType: DijitTooltipDialog
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTooltipDialog: aBlock [
	" Dojo widget: dijit.TooltipDialog "

	self dojoTooltipDialog with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTree [
	" Dojo widget: dijit.Tree "

	^ self div dojoType: DijitTree
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoTree: aBlock [
	" Dojo widget: dijit.Tree "

	self dojoTree with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoValidationTextBox [
	" Dojo widget: dijit.form.ValidationTextBox "

	^ self textInput dojoType: DijitValidationTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoValidationTextBox: aBlock [
	" Dojo widget: dijit.form.ValidationTextBox "

	self dojoValidationTextBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoVerticalRule [
	" Dojo widget: dijit.form.VerticalRule "

	^ self div dojoType: DijitVerticalRule
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoVerticalRule: aBlock [
	" Dojo widget: dijit.form.VerticalRule "

	self dojoVerticalRule with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoVerticalRuleLabels [
	" Dojo widget: dijit.form.VerticalRuleLabels "

	^ self div dojoType: DijitVerticalRuleLabels
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoVerticalRuleLabels: aBlock [
	" Dojo widget: dijit.form.VerticalRuleLabels "

	self dojoVerticalRuleLabels with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoVerticalSlider [
	" Dojo widget: dijit.form.VerticalSlider "

	^ self div dojoType: DijitVerticalSlider
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WAHtmlCanvas >> dojoVerticalSlider: aBlock [
	" Dojo widget: dijit.form.VerticalSlider "

	self dojoVerticalSlider with: aBlock
]
