Extension { #name : #WARenderCanvas }

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoAccordionContainer [
	" Dojo widget: dijit.layout.AccordionContainer "

	^ self div dojoType: DijitAccordionContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoAccordionContainer: aBlock [
	" Dojo widget: dijit.layout.AccordionContainer "

	self dojoAccordionContainer with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoAccordionPane [
	" Dojo widget: dijit.layout.AccordionPane "

	^ self div dojoType: DijitAccordionPane
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoAccordionPane: aBlock [
	" Dojo widget: dijit.layout.AccordionPane "

	self dojoAccordionPane with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoBorderContainer [
	" Dojo widget: dijit.layout.BorderContainer "

	^ self div dojoType: DijitBorderContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoBorderContainer: aBlock [
	" Dojo widget: dijit.layout.BorderContainer "

	self dojoBorderContainer with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoButton [
	" Dojo widget: dijit.form.Button "

	^ self button dojoType: DijitButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoButton: aBlock [
	" Dojo widget: dijit.form.Button "

	self dojoButton with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoCalendar [
	" Dojo widget: dijit.Calendar "

	^ self div dojoType: DijitCalendar
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoCalendar: aBlock [
	" Dojo widget: dijit.Calendar "

	self dojoCalendar with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoCheckBox [
	" Dojo widget: dijit.form.CheckBox "

	^ self div dojoType: DijitCheckBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoCheckBox: aBlock [
	" Dojo widget: dijit.form.CheckBox "

	self dojoCheckBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoCheckedMenuItem [
	" Dojo widget: dijit.CheckedMenuItem "

	^ self div dojoType: DijitCheckedMenuItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoCheckedMenuItem: aBlock [
	" Dojo widget: dijit.CheckedMenuItem "

	self dojoCheckedMenuItem with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoColorPalette [
	" Dojo widget: dijit.ColorPalette "

	^ self div dojoType: DijitColorPalette
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoColorPalette: aBlock [
	" Dojo widget: dijit.ColorPalette "

	self dojoColorPalette with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoComboBox [
	" Dojo widget: dijit.form.ComboBox "

	^ self textInput dojoType: DijitComboBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoComboBox: aBlock [
	" Dojo widget: dijit.form.ComboBox "

	self dojoComboBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoComboButton [
	" Dojo widget: dijit.form.ComboButton "

	^ self div dojoType: DijitComboButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoComboButton: aBlock [
	" Dojo widget: dijit.form.ComboButton "

	self dojoComboButton with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoContentPane [
	" Dojo widget: dijit.layout.ContentPane "

	^ self div dojoType: DijitContentPane
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoContentPane: aBlock [
	" Dojo widget: dijit.layout.ContentPane "

	self dojoContentPane with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoCurrencyTextBox [
	" Dojo widget: dijit.form.CurrencyTextBox "

	^ self textInput dojoType: DijitCurrencyTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoCurrencyTextBox: aBlock [
	" Dojo widget: dijit.form.CurrencyTextBox "

	self dojoCurrencyTextBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoDateTextBox [
	" Dojo widget: dijit.form.DateTextBox "

	^ self textInput dojoType: DijitDateTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoDateTextBox: aBlock [
	" Dojo widget: dijit.form.DateTextBox "

	self dojoDateTextBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoDateTimeTextBox [
	" Dojo widget: dijit.form.DateTimeTextBox "

	^ self textInput dojoType: DijitDateTimeTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoDateTimeTextBox: aBlock [
	" Dojo widget: dijit.form.DateTimeTextBox "

	self dojoDateTimeTextBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoDeclaration [
	" Dojo widget: dijit.Declaration "

	^ self div dojoType: DijitDeclaration
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoDeclaration: aBlock [
	" Dojo widget: dijit.Declaration "

	self dojoDeclaration with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoDialog [
	" Dojo widget: dijit.Dialog "

	^ self div dojoType: DijitDialog
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoDialog: aBlock [
	" Dojo widget: dijit.Dialog "

	self dojoDialog with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoDialogUnderlay [
	" Dojo widget: dijit.DialogUnderlay "

	^ self div dojoType: DijitDialogUnderlay
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoDialogUnderlay: aBlock [
	" Dojo widget: dijit.DialogUnderlay "

	self dojoDialogUnderlay with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoDropDownButton [
	" Dojo widget: dijit.form.DropDownButton "

	^ self div dojoType: DijitDropDownButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoDropDownButton: aBlock [
	" Dojo widget: dijit.form.DropDownButton "

	self dojoDropDownButton with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoEditor [
	" Dojo widget: dijit.Editor "

	^ self div dojoType: DijitEditor
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoEditor: aBlock [
	" Dojo widget: dijit.Editor "

	self dojoEditor with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoEditorRichText [
	" Dojo widget: dijit.editor.RichText "

	^ self div dojoType: DijitRichText
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoEditorRichText: aBlock [
	" Dojo widget: dijit.editor.RichText "

	self dojoEditorRichText with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoFilteringSelect [
	" Dojo widget: dijit.form.FilteringSelect "

	^ self textInput dojoType: DijitFilteringSelect
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoFilteringSelect: aBlock [
	" Dojo widget: dijit.form.FilteringSelect "

	self dojoFilteringSelect with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoForm [
	" Dojo widget: dijit.form.Form "

	^ (self brush: DojoWidgetFormTag new) dojoType: DijitForm
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoForm: aBlock [
	" Dojo widget: dijit.form.Form "

	self dojoForm with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoFormSelectWidget [
	" Dojo widget: dijit.form.FormSelectWidget "

	^ self div dojoType: DijitFormSelectWidget
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoFormSelectWidget: aBlock [
	" Dojo widget: dijit.form.FormSelectWidget "

	self dojoFormSelectWidget with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoHorizontalRule [
	" Dojo widget: dijit.form.HorizontalRule "

	^ self div dojoType: DijitHorizontalRule
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoHorizontalRule: aBlock [
	" Dojo widget: dijit.form.HorizontalRule "

	self dojoHorizontalRule with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoHorizontalRuleLabels [
	" Dojo widget: dijit.form.HorizontalRuleLabels "

	^ self div dojoType: DijitHorizontalRuleLabels
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoHorizontalRuleLabels: aBlock [
	" Dojo widget: dijit.form.HorizontalRuleLabels "

	self dojoHorizontalRuleLabels with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoHorizontalSlider [
	" Dojo widget: dijit.form.HorizontalSlider "

	^ self div dojoType: DijitHorizontalSlider
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoHorizontalSlider: aBlock [
	" Dojo widget: dijit.form.HorizontalSlider "

	self dojoHorizontalSlider with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoInlineEditBox [
	" Dojo widget: dijit.InlineEditBox "

	^ self div dojoType: DijitInlineEditBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoInlineEditBox: aBlock [
	" Dojo widget: dijit.InlineEditBox "

	self dojoInlineEditBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoLayoutContainer [
	" Dojo widget: dijit.layout.LayoutContainer "

	^ self div dojoType: DijitLayoutContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoLayoutContainer: aBlock [
	" Dojo widget: dijit.layout.LayoutContainer "

	self dojoLayoutContainer with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoLayoutWidget [
	" Dojo widget: dijit.layout.LayoutWidget "

	^ self div dojoType: DijitLayoutWidget
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoLayoutWidget: aBlock [
	" Dojo widget: dijit.layout.LayoutWidget "

	self dojoLayoutWidget with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoLinkPane [
	" Dojo widget: dijit.layout.LinkPane "

	^ self div dojoType: DijitLinkPane
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoLinkPane: aBlock [
	" Dojo widget: dijit.layout.LinkPane "

	self dojoLinkPane with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoMappedTextBox [
	" Dojo widget: dijit.form.MappedTextBox "

	^ self textInput dojoType: DijitMappedTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoMappedTextBox: aBlock [
	" Dojo widget: dijit.form.MappedTextBox "

	self dojoMappedTextBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoMenu [
	" Dojo widget: dijit.Menu "

	^ self div dojoType: DijitMenu
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoMenu: aBlock [
	" Dojo widget: dijit.Menu "

	self dojoMenu with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoMenuBar [
	" Dojo widget: dijit.MenuBar "

	^ self div dojoType: DijitMenuBar
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoMenuBar: aBlock [
	" Dojo widget: dijit.MenuBar "

	self dojoMenuBar with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoMenuBarItem [
	" Dojo widget: dijit.MenuBarItem "

	^ self div dojoType: DijitMenuBarItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoMenuBarItem: aBlock [
	" Dojo widget: dijit.MenuBarItem "

	self dojoMenuBarItem with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoMenuBase [
	" Dojo widget: dijit.MenuBase "

	^ self div dojoType: DijitMenuBase
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoMenuBase: aBlock [
	" Dojo widget: dijit.MenuBase "

	self dojoMenuBase with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoMenuItem [
	" Dojo widget: dijit.MenuItem "

	^ self div dojoType: DijitMenuItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoMenuItem: aBlock [
	" Dojo widget: dijit.MenuItem "

	self dojoMenuItem with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoMenuSeparator [
	" Dojo widget: dijit.MenuSeparator "

	^ self div dojoType: DijitMenuSeparator
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoMenuSeparator: aBlock [
	" Dojo widget: dijit.MenuSeparator "

	self dojoMenuSeparator with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoMultiSelect [
	" Dojo widget: dijit.form.MultiSelect "

	^ self div dojoType: DijitMultiSelect
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoMultiSelect: aBlock [
	" Dojo widget: dijit.form.MultiSelect "

	self dojoMultiSelect with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoNumberSpinner [
	" Dojo widget: dijit.form.NumberSpinner "

	^ self textInput dojoType: DijitNumberSpinner
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoNumberSpinner: aBlock [
	" Dojo widget: dijit.form.NumberSpinner "

	self dojoNumberSpinner with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoNumberTextBox [
	" Dojo widget: dijit.form.NumberTextBox "

	^ self textInput dojoType: DijitNumberTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoNumberTextBox: aBlock [
	" Dojo widget: dijit.form.NumberTextBox "

	self dojoNumberTextBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoPopupMenuBarItem [
	" Dojo widget: dijit.PopupMenuBarItem "

	^ self div dojoType: DijitPopupMenuBarItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoPopupMenuBarItem: aBlock [
	" Dojo widget: dijit.PopupMenuBarItem "

	self dojoPopupMenuBarItem with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoPopupMenuItem [
	" Dojo widget: dijit.PopupMenuItem "

	^ self div dojoType: DijitPopupMenuItem
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoPopupMenuItem: aBlock [
	" Dojo widget: dijit.PopupMenuItem "

	self dojoPopupMenuItem with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoProgressBar [
	" Dojo widget: dijit.ProgressBar "

	^ self div dojoType: DijitProgressBar
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoProgressBar: aBlock [
	" Dojo widget: dijit.ProgressBar "

	self dojoProgressBar with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoRadioButton [
	" Dojo widget: dijit.form.RadioButton "

	^ self div dojoType: DijitRadioButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoRadioButton: aBlock [
	" Dojo widget: dijit.form.RadioButton "

	self dojoRadioButton with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoRangeBoundTextBox [
	" Dojo widget: dijit.form.RangeBoundTextBox "

	^ self textInput dojoType: DijitRangeBoundTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoRangeBoundTextBox: aBlock [
	" Dojo widget: dijit.form.RangeBoundTextBox "

	self dojoRangeBoundTextBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoScrollingTabController [
	" Dojo widget: dijit.layout.ScrollingTabController "

	^ self div dojoType: DijitScrollingTabController
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoScrollingTabController: aBlock [
	" Dojo widget: dijit.layout.ScrollingTabController "

	self dojoScrollingTabController with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoSelect [
	" Dojo widget: dijit.form.Select "

	^ self div dojoType: DijitSelect
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoSelect: aBlock [
	" Dojo widget: dijit.form.Select "

	self dojoSelect with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoSimpleTextarea [
	" Dojo widget: dijit.form.SimpleTextarea "

	^ self textArea dojoType: DijitSimpleTextarea
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoSimpleTextarea: aBlock [
	" Dojo widget: dijit.form.SimpleTextarea "

	self dojoSimpleTextarea with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoSpinner [
	" Dojo widget: dijit.form.Spinner "

	^ self textInput dojoType: DijitSpinner
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoSpinner: aBlock [
	" Dojo widget: dijit.form.Spinner "

	self dojoSpinner with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoSplitContainer [
	" Dojo widget: dijit.layout.SplitContainer "

	^ self div dojoType: DijitSplitContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoSplitContainer: aBlock [
	" Dojo widget: dijit.layout.SplitContainer "

	self dojoSplitContainer with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoStackContainer [
	" Dojo widget: dijit.layout.StackContainer "

	^ self div dojoType: DijitStackContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoStackContainer: aBlock [
	" Dojo widget: dijit.layout.StackContainer "

	self dojoStackContainer with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoStackController [
	" Dojo widget: dijit.layout.StackController "

	^ self div dojoType: DijitStackController
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoStackController: aBlock [
	" Dojo widget: dijit.layout.StackController "

	self dojoStackController with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoSubmitButton [
	" Dojo widget: dijit.form.Button "
	" does not use WASubmitButtonTag, because Dojo uses the contents of the <button> tag as label "

	^ self button type: 'submit';
		dojoType: DijitButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoSubmitButton: aBlock [
	" Dojo widget: dijit.form.Button "

	self dojoSubmitButton with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTabContainer [
	" Dojo widget: dijit.layout.TabContainer "

	^ self div dojoType: DijitTabContainer
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTabContainer: aBlock [
	" Dojo widget: dijit.layout.TabContainer "

	self dojoTabContainer with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTabContainerBase [
	" Dojo widget: dijit.layout.TabContainerBase "

	^ self div dojoType: DijitTabContainerBase
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTabContainerBase: aBlock [
	" Dojo widget: dijit.layout.TabContainerBase "

	self dojoTabContainerBase with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTabController [
	" Dojo widget: dijit.layout.TabController "

	^ self div dojoType: DijitTabController
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTabController: aBlock [
	" Dojo widget: dijit.layout.TabController "

	self dojoTabController with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTextBox [
	" Dojo widget: dijit.form.TextBox "

	^ self textInput dojoType: DijitTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTextBox: aBlock [
	" Dojo widget: dijit.form.TextBox "

	self dojoTextBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTextarea [
	" Dojo widget: dijit.form.Textarea "

	^ self textArea dojoType: DijitTextarea
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTextarea: aBlock [
	" Dojo widget: dijit.form.Textarea "

	self dojoTextarea with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTimeTextBox [
	" Dojo widget: dijit.form.TimeTextBox "

	^ self textInput dojoType: DijitTimeTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTimeTextBox: aBlock [
	" Dojo widget: dijit.form.TimeTextBox "

	self dojoTimeTextBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTitlePane [
	" Dojo widget: dijit.TitlePane "

	^ self div dojoType: DijitTitlePane
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTitlePane: aBlock [
	" Dojo widget: dijit.TitlePane "

	self dojoTitlePane with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoToggleButton [
	" Dojo widget: dijit.form.ToggleButton "

	^ self div dojoType: DijitToggleButton
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoToggleButton: aBlock [
	" Dojo widget: dijit.form.ToggleButton "

	self dojoToggleButton with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoToolbar [
	" Dojo widget: dijit.Toolbar "

	^ self div dojoType: DijitToolbar
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoToolbar: aBlock [
	" Dojo widget: dijit.Toolbar "

	self dojoToolbar with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoToolbarSeparator [
	" Dojo widget: dijit.ToolbarSeparator "

	^ self div dojoType: DijitToolbarSeparator
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoToolbarSeparator: aBlock [
	" Dojo widget: dijit.ToolbarSeparator "

	self dojoToolbarSeparator with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTooltip [
	" Dojo widget: dijit.Tooltip "

	^ self div dojoType: DijitTooltip
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTooltip: aBlock [
	" Dojo widget: dijit.Tooltip "

	self dojoTooltip with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTooltipDialog [
	" Dojo widget: dijit.TooltipDialog "

	^ self div dojoType: DijitTooltipDialog
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTooltipDialog: aBlock [
	" Dojo widget: dijit.TooltipDialog "

	self dojoTooltipDialog with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTree [
	" Dojo widget: dijit.Tree "

	^ self div dojoType: DijitTree
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoTree: aBlock [
	" Dojo widget: dijit.Tree "

	self dojoTree with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoValidationTextBox [
	" Dojo widget: dijit.form.ValidationTextBox "

	^ self textInput dojoType: DijitValidationTextBox
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoValidationTextBox: aBlock [
	" Dojo widget: dijit.form.ValidationTextBox "

	self dojoValidationTextBox with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoVerticalRule [
	" Dojo widget: dijit.form.VerticalRule "

	^ self div dojoType: DijitVerticalRule
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoVerticalRule: aBlock [
	" Dojo widget: dijit.form.VerticalRule "

	self dojoVerticalRule with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoVerticalRuleLabels [
	" Dojo widget: dijit.form.VerticalRuleLabels "

	^ self div dojoType: DijitVerticalRuleLabels
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoVerticalRuleLabels: aBlock [
	" Dojo widget: dijit.form.VerticalRuleLabels "

	self dojoVerticalRuleLabels with: aBlock
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoVerticalSlider [
	" Dojo widget: dijit.form.VerticalSlider "

	^ self div dojoType: DijitVerticalSlider
]

{ #category : #'*DojoToolkit-Widgets-generated' }
WARenderCanvas >> dojoVerticalSlider: aBlock [
	" Dojo widget: dijit.form.VerticalSlider "

	self dojoVerticalSlider with: aBlock
]
